### PR TITLE
Add completed task list section

### PR DESCRIPTION
**Pull request by sandhyak-tech**

### CODE REVIEW

**Comment by sandhyak-tech** [comment]
[https://github.com/vaishnav-sh/todo-app/issues/1](url)

**Comment by sandhyak-tech** [comment]
[https://user-images.githubusercontent.com/59618814/136240349-d7bcffa7-83c5-4dd9-a9d4-0a1425dbc770.png](url)

**Comment by sandhyak-tech** [comment]
image

**Comment by vaishnav-sh** [comment]
Good job!

**Pull request merged**
