### PR TITLE
Added Dark, Light Mode

### PR DESCRIPTION
**Pull request by Ashwani132003**
Changes after pressing button
Screenshot (245)
Screenshot (247)

### CODE REVIEW

**Comment by vaishnav-sh** [comment]
Can you replace the text with an icon?

**Comment by Ashwani132003** [comment]
@vaishnav-sh  ya, just a moment.

**Comment by Ashwani132003** [comment]
@vaishnav-sh  Is it okay?
Screenshot (249)

**Comment by Ashwani132003** [comment]
@vaishnav-sh Hope you will like it, please merge it and if still any changes required then please tell me, I am working on its UI improvement so will do the same along with. Thanks

**Pull request merged**
